name: Create Dated File

on:
  repository_dispatch:
    types: [create-dated-file]

jobs:
  create_file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dated file in content directory
        run: |
          mkdir -p content
          now=$(date +"%Y-%m-%d-%H-%M-%S")
          filename="content/$now.md"
          echo "# New Blog Post" > $filename
          echo "" >> $filename
          echo "This post was generated automatically." >> $filename
          echo "" >> $filename
          echo "Date: $(date +'%Y-%m-%d %H:%M:%S')" >> $filename
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add content/*.md
          git commit -m "Create dated file: $filename"
          git push
